name: generate-snake-game-from-github-contribution-grid

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Game SVG
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Skill-g

      - name: Save Snake Game SVG
        run: |
          cp ./snake.svg dist/github-contribution-grid-snake.svg
        working-directory: ${{ github.workspace }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
